apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secrets.secretProviderClass }}
  labels:
    {{- include "usermgmt.labels" . | nindent 4 }}
spec:
  provider: aws

  parameters:
    usePodIdentity: "true"
    objects: |
      - objectName: "{{ .Values.secrets.awsSecretName }}"
        objectType: "secretsmanager"
        jmesPath:
          - path: "DB_USERNAME"
            objectAlias: "DB_USERNAME"
          - path: "DB_PASSWORD"
            objectAlias: "DB_PASSWORD"

  secretObjects:
    - secretName: {{ .Values.secrets.k8sSecretName }}
      type: Opaque
      data:
        - objectName: DB_USERNAME
          key: DB_USERNAME
        - objectName: DB_PASSWORD
          key: DB_PASSWORD