apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: usermgmt-ui
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tcollins520/aws-eks-platform-engineering_argocd-gitops.git
    targetRevision: main
    path: helm-argocd/usermgmt-chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true    # Auto-delete resources not in Git
      selfHeal: true # Auto-sync if drift detected
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true