{{- if .Values.ingress.enabled }}

apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: {{ .Release.Name }}

  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

  annotations:

    alb.ingress.kubernetes.io/load-balancer-name: "{{ .Values.ingress.loadBalancerName }}"

    alb.ingress.kubernetes.io/scheme: "{{ .Values.ingress.scheme }}"

    alb.ingress.kubernetes.io/target-type: "{{ .Values.ingress.targetType }}"

    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443},{"HTTP":80}]'

    alb.ingress.kubernetes.io/certificate-arn: "{{ .Values.ingress.certificateArn }}"

    alb.ingress.kubernetes.io/ssl-redirect: "{{ .Values.ingress.sslRedirect }}"

    alb.ingress.kubernetes.io/healthcheck-path: "{{ .Values.ingress.healthcheck.path }}"

    alb.ingress.kubernetes.io/healthcheck-protocol: "{{ .Values.ingress.healthcheck.protocol }}"

    alb.ingress.kubernetes.io/healthcheck-port: "{{ .Values.ingress.healthcheck.port }}"

    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "{{ .Values.ingress.healthcheck.interval }}"

    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "{{ .Values.ingress.healthcheck.timeout }}"

    alb.ingress.kubernetes.io/healthy-threshold-count: "{{ .Values.ingress.healthcheck.healthyThreshold }}"

    alb.ingress.kubernetes.io/unhealthy-threshold-count: "{{ .Values.ingress.healthcheck.unhealthyThreshold }}"

    alb.ingress.kubernetes.io/success-codes: "{{ .Values.ingress.healthcheck.successCodes }}"

    external-dns.alpha.kubernetes.io/hostname: "{{ .Values.ingress.host }}"

spec:

  ingressClassName: {{ .Values.ingress.className }}

  rules:

    - host: {{ .Values.ingress.host }}

      http:

        paths:

          - path: {{ .Values.ingress.path }}

            pathType: {{ .Values.ingress.pathType }}

            backend:

              service:

                name: {{ .Values.service.name }}

                port:

                  number: {{ .Values.service.port }}

{{- end }}